### Populates the database
POST http://localhost:7070/api/skilessons/populate
Content-Type: application/json

### Shows all the lessons
GET http://localhost:7070/api/skilessons
Content-Type: application/json

### Get lesson with ID 1 (This will succeed 200)
GET http://localhost:7070/api/skilessons/1
Content-Type: application/json

### Get lesson with ID 42 (This will fail 404)
GET http://localhost:7070/api/skilessons/42
Content-Type: application/json

### Add a new lesson
POST http://localhost:7070/api/skilessons
Content-Type: application/json

{
  "starttime": [
    2025,
    4,
    7,
    11,
    37,
    52,
    385537000
  ],
  "endtime": [
    2025,
    4,
    7,
    15,
    37,
    52,
    385537000
  ],
  "longitude": 46.5405,
  "latitude": 12.1357,
  "name": "Cortina d'Ampezzo, Italy",
  "price": 425.00,
  "level": "BEGINNER",
  "instructor": null
}

### Update a lesson with ID 1 (This will succeed 200)
PUT http://localhost:7070/api/skilessons/1
Content-Type: application/json

{
  "price": 780.00
}

### Update a lesson with ID 42 (This will fail 404)
PUT http://localhost:7070/api/skilessons/42
Content-Type: application/json

{
  "price": 780.00
}

### Delete a lesson with ID 1 (This will succeed 204)
DELETE http://localhost:7070/api/skilessons/1
Content-Type: application/json

### Delete a lesson with ID 42 (This will fail 404)
DELETE http://localhost:7070/api/skilessons/42
Content-Type: application/json

### Assign an instructor with ID 3 to a lesson with ID 2 (This will succeed 200)
PUT http://localhost:7070/api/skilessons/2/instructors/3
Content-Type: application/json

### Assign an instructor with ID 42 to a lesson with ID 2 (This will fail 404)
PUT http://localhost:7070/api/skilessons/2/instructors/42
Content-Type: application/json
